### ISSUE TITLE
Feil bruker dukker opp i jti

### ISSUE THREAD

**Issue by Robert-Larsen** [navikt/stub-oidc-provider#5]
1. Logger inn som Aremark uten ID-porten, på nivå 3.
2. Dekoder tokenet. Da står alltid min e-postadresse i jti. Vi har forsøkt på tre andre team-medlemmer sine maskiner, som de var logget på som seg selv, og min e-postadresse dukker alltid opp i "jti". Det burde vel ha vært deres egen e-post?

**Comment by tronghn** [comment]
Grunnen til at dette skjer er at logins blir cachet i provideren der keyen kun er basert på brukeren/subjektet som man logger seg på med.

Den første som logger seg på med en gitt bruker vil dermed være knyttet til denne brukeren så lenge cachen ikke tømmes.
